services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: redwoodiloilo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

volumes:
  pgdata:

networks:
  postgres-network:
    external: true