services:
  backup-agent:
    image: emmanueljomer/backup-agent:latest
    container_name: backup-agent
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      AWS_REGION: "${AWS_REGION:-ap-southeast-2}"
    volumes:
      - ./backups:/app/backups
      - ./appsettings.json:/app/appsettings.json:ro
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
